#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: ac54u_base

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install autopoint autoconf automake bison curl build-essential flex gawk gettext gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils mc cmake unzip nano libncurses5-dev libltdl-dev lrzsz
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/nns2020/padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        #wget https://github.com/nns2020/byl/raw/master/ubt18/mipsel-linux-uclibc.tar.gz
        #tar -xvf mipsel-linux-uclibc.tar.gz
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: ac54u_base
      run: |
        ##############################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        cd /opt/rt-n56u/toolchain-mipsel
        sudo ./clean_sources
        sudo ./clean_toolchain 
        sudo ./build_toolchain
        tar zcvf 2.tar.gz toolchain-3.4.x
        sudo mv -f 2.tar.gz /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-tool
        path: /opt/images
